<a href="https://colab.research.google.com/github/jacobletsinger/MAT422/blob/main/HW1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1.2


1.2.1. Linear spaces \\
1.2.2. Orthogonality \\
1.2.3. Gram–Schmidt process \\
1.2.4. Eigenvalues and eigenvectors \\

### 1.2.1 Linear Spaces

In [ ]:
import numpy as np

# Different arrays in numpy
x = np.linspace(0, 1, 5)
y = np.zeros(5)
z = np.ones(5)
t = np.full(5, 16)

u = np.arange(0,5)
v = np.empty_like(u)
w = np.asarray([1,2,4,6,5])

coords = np.array((x,y,z,t))
coords2 = np.meshgrid(u,w)

print(coords)
print(coords2)

[[ 0.    0.25  0.5   0.75  1.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 1.    1.    1.    1.    1.  ]
 [16.   16.   16.   16.   16.  ]]
[array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]]), array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6],
       [5, 5, 5, 5, 5]])]


In [ ]:
# Array manipulation and data access
print(coords[0,4])
print(coords[1])
coords[2] = np.zeros(5)
coords[2,3] = 1
print(coords)


print(coords2[0][4])
print(coords2[1])
print(coords2[1][2,3])


1.0
[0. 0. 0. 0. 0.]
[[ 0.    0.25  0.5   0.75  1.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.  ]
 [16.   16.   16.   16.   16.  ]]
[0 1 2 3 4]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [4 4 4 4 4]
 [6 6 6 6 6]
 [5 5 5 5 5]]
4


In [ ]:
# Matrices in Numpy and associated functions
A = np.asmatrix(([1,6,2],[-7,9,2],[1,0,-6]))
print(A)
print(A.T)
print(A[0,0])
print(np.trace(A))
print(np.linalg.inv(A))

[[ 1  6  2]
 [-7  9  2]
 [ 1  0 -6]]
[[ 1 -7  1]
 [ 6  9  0]
 [ 2  2 -6]]
1
4
[[ 0.17307692 -0.11538462  0.01923077]
 [ 0.12820513  0.02564103  0.05128205]
 [ 0.02884615 -0.01923077 -0.16346154]]


### 1.2.2. Orthogonality

In [ ]:
# Dot product and norm with numpy

a = np.array([1,1,2])
b = np.array([4,6,1])

print(np.dot(a,b))
print(np.linalg.norm(a))
print(np.linalg.norm(b))

12
2.449489742783178
7.280109889280518


In [ ]:
# Angle between any two vectors

def angle_between_vectors(a,b):
  return np.arccos(np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b)))

print(angle_between_vectors(a,b)*180/np.pi, " Degrees")

47.706656136985565  Degrees


In [ ]:
# A function that checks if two vectors are orthogonal

def check_orthogonality(a,b):
  return True if np.dot(a,b) == 0 else False

c = (1,0)
d = (0,1)

print(check_orthogonality(a,b))
print(check_orthogonality(c,d))
print(angle_between_vectors(c,d)*180/np.pi, " Degrees")

False
True
90.0  Degrees


In [ ]:
# The Projection of vector b onto another vector a

def projection(a,b):
  return np.multiply((np.dot(a,b) / (np.linalg.norm(a)**2)), a)

print(projection(a,b))
print(projection(b,a))

[2. 2. 4.]
[0.90566038 1.35849057 0.22641509]


### 1.2.3. Gram–Schmidt process

In [ ]:
# Function adapting the Gram-Shmidt algorithm that constructs an orthogonal basis

def gram_schmidt(A):
  V = np.float64(np.copy(A))
  U = np.float64(np.copy(A))

  for i in range(0, V.shape[1]):
    v = V[:,i]

    u = v
    for k in range(0,i):
      u -= projection(V[:,k],v)
    U[:,i] = u / np.linalg.norm(u)

  return U

A = np.asmatrix(([3,2,0],[1,2,0],[0,0,1]))
print(A)
print(gram_schmidt(A))

[[3 2 0]
 [1 2 0]
 [0 0 1]]
[[ 0.9486833  -0.31622777  0.        ]
 [ 0.31622777  0.9486833   0.        ]
 [ 0.          0.          1.        ]]


### 1.2.4 Eigenvalues and eigenvectors

In [ ]:
#Eigenvalues and eigenvectors of matrix with numpy

M = np.asmatrix([[1,1,3,5],[2,-3,5,2],[-1,0,9,-3],[-9,0,1,3]])

eigenvalues, eigenvectors = np.linalg.eig(M)
print(eigenvalues)
print(eigenvectors)

[-3.5369817 +0.j          2.06600726+7.33145344j  2.06600726-7.33145344j
  9.40496718+0.j        ]
[[ 0.08051474+0.j         -0.09646418+0.57334064j -0.09646418-0.57334064j
   0.2388482 +0.j        ]
 [-0.99059247+0.j         -0.1176492 +0.27465442j -0.1176492 -0.27465442j
   0.36098112+0.j        ]
 [ 0.03178451+0.j         -0.195068  -0.12356392j -0.195068  +0.12356392j
   0.87938169+0.j        ]
 [ 0.10598901+0.j         -0.7206797 +0.j         -0.7206797 -0.j
  -0.19832298+0.j        ]]


In [ ]:
# Singular Value Decomposition of a matrix with numpy

U, D, VT, = np.linalg.svd(M)

print(U * np.diag(D) * VT)

[[ 1.00000000e+00  1.00000000e+00  3.00000000e+00  5.00000000e+00]
 [ 2.00000000e+00 -3.00000000e+00  5.00000000e+00  2.00000000e+00]
 [-1.00000000e+00  2.79595547e-16  9.00000000e+00 -3.00000000e+00]
 [-9.00000000e+00  5.08957403e-16  1.00000000e+00  3.00000000e+00]]
