<a href="https://colab.research.google.com/github/jacobletsinger/MAT422/blob/main/HW1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 4

1.4.1. Singular value decomposition

1.4.2. Low-rank matrix approximations

1.4.3. Principal component analysis


### 1.4.1. Singular value decomposition

Any $m \times n$ matrix can be factored into a rotation followed by a scaling which is followed by and second rotation. Let $U$ be an $m \times m$, let $V$ be an $n \times n$, and let $S$ be an $m \times n$ diagonal matrix with not negative components, then $M = USV$. There are functions in numpy that allow one to do this.


In [23]:
import numpy as np

M = np.array([(9, -4,4),(2,-3,0),(6,-5,3),(7,0,1)])

U, S_, V = np.linalg.svd(M)
S = np.zeros((4, 3), dtype=complex)

S[:3, :3] = np.diag(S_)


print(U)
print(S)
print(V)
print(np.dot(U, np.dot(S, V)))

[[-0.70420785  0.03359741 -0.41297086 -0.57655666]
 [-0.19417524 -0.41503827  0.8095825  -0.36689969]
 [-0.53925762 -0.48968563 -0.07157857  0.68138514]
 [-0.41903281  0.76604336  0.41098389  0.26207121]]
[[15.0663738 +0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j  4.07278522+0.j  0.        +0.j]
 [ 0.        +0.j  0.        +0.j  1.5546064 +0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j]]
[[-0.85587924  0.40458609 -0.32215032]
 [ 0.46564937  0.87388683 -0.13961549]
 [ 0.22503643 -0.26950309 -0.93633685]]
[[ 9.00000000e+00+0.j -4.00000000e+00+0.j  4.00000000e+00+0.j]
 [ 2.00000000e+00+0.j -3.00000000e+00+0.j  1.12743204e-16+0.j]
 [ 6.00000000e+00+0.j -5.00000000e+00+0.j  3.00000000e+00+0.j]
 [ 7.00000000e+00+0.j  1.46679161e-15+0.j  1.00000000e+00+0.j]]


### 1.4.2. Low-rank matrix approximations
A low rank matrix approximation is the approximation of a given matrix with one of lower rank. This can be found using the components of an SVD transformation. In particular, the best rank $k$ approximation of a matrix $A$ is given by the sum
\begin{equation}
A_k=\sum_{i=1}^k \sigma_i u_i v^T_i
\end{equation}

where $u_i$, $\sigma_i$ and $v_i$ are the $ith$ columns of $U$, $S$, and $V$ respectively and $A_k$ is the $kth$ column of the approximation.

In [ ]:
M = np.array([(9, -4,4),(2,-3,0),(6,-5,3),(7,0,1)])

U, S_, V = np.linalg.svd(M)

k = 3




### 1.4.3. Principal component analysis
